// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYuvEXcREM-B3u222XiDrNfu2xNce0f0',
    appId: '1:52450359227:web:ccb1dac49fa7131424769e',
    messagingSenderId: '52450359227',
    projectId: 'hrmsmart-e63c7',
    authDomain: 'hrmsmart-e63c7.firebaseapp.com',
    storageBucket: 'hrmsmart-e63c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9i0aH1-2zNn_BS9MbyZkjHKxSk029_dE',
    appId: '1:52450359227:android:7248ce44a07808c124769e',
    messagingSenderId: '52450359227',
    projectId: 'hrmsmart-e63c7',
    storageBucket: 'hrmsmart-e63c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKS8J1YnuIl4Xm81kHBZRXIRuKfyhaldk',
    appId: '1:52450359227:ios:bf571a035efecea524769e',
    messagingSenderId: '52450359227',
    projectId: 'hrmsmart-e63c7',
    storageBucket: 'hrmsmart-e63c7.firebasestorage.app',
    androidClientId: '52450359227-c9faac27k8qb62vhfd43r1dj05k8ja5v.apps.googleusercontent.com',
    iosClientId: '52450359227-3qsuod37lnurt3pl22ecsps0i8fmfbms.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKS8J1YnuIl4Xm81kHBZRXIRuKfyhaldk',
    appId: '1:52450359227:ios:bf571a035efecea524769e',
    messagingSenderId: '52450359227',
    projectId: 'hrmsmart-e63c7',
    storageBucket: 'hrmsmart-e63c7.firebasestorage.app',
    androidClientId: '52450359227-c9faac27k8qb62vhfd43r1dj05k8ja5v.apps.googleusercontent.com',
    iosClientId: '52450359227-3qsuod37lnurt3pl22ecsps0i8fmfbms.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbYuvEXcREM-B3u222XiDrNfu2xNce0f0',
    appId: '1:52450359227:web:64556280912fdb5624769e',
    messagingSenderId: '52450359227',
    projectId: 'hrmsmart-e63c7',
    authDomain: 'hrmsmart-e63c7.firebaseapp.com',
    storageBucket: 'hrmsmart-e63c7.firebasestorage.app',
  );
}
